version: "3.8"

services:
  catraca-web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./usuarios:/app/usuarios
      - ./uploads:/app/uploads
      - ./catraca_virtual.db:/app/catraca_virtual.db
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
